### ISSUE TITLE
ERROR when installing dependencies from requirements.txt

### ISSUE THREAD

**Issue by dekacypher** [rishikonapure/Cryptocurrency-Sentiment-Analysis#1]
`!pip install -r /content/Cryptocurrency-Sentiment-Analysis/requirements.txt`
`
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting aiohttp==3.7.4.post0
  Downloading aiohttp-3.7.4.post0-cp37-cp37m-manylinux2014_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 5.1 MB/s 
Requirement already satisfied: alabaster==0.7.12 in /usr/local/lib/python3.7/dist-packages (from -r /content/Cryptocurrency-Sentiment-Analysis/requirements.txt (line 2)) (0.7.12)
ERROR: Could not find a version that satisfies the requirement anaconda-client==1.7.2 (from versions: 1.1.1, 1.2.2)
ERROR: No matching distribution found for anaconda-client==1.7.2`

I get this error code when trying to install dependencies

<img width="224" alt="Screen Shot 2022-10-30 at 19 21 53" src="https://user-images.githubusercontent.com/87758754/198894927-0e5377f2-35d3-47e8-b90e-4e7db660f403.png">
#

**Comment by rishikonapure** [comment]
@dekacypher requirements.txt lists `anaconda-client==1.7.2` does indeed exist in pip/Pypi, you can solve this issue by  installing anaconda-client through `conda`
